import { cn } from "@/lib/utils"
import { StatusBadge } from "./StatusBadge"

export type MaxIDCardVariant = "active" | "inactive"

interface MaxIDCardProps {
  variant?: MaxIDCardVariant
  dateGenerated?: string
  generatedBy?: string
  onViewCard?: () => void
  onExportCard?: () => void
  onGenerateCard?: () => void
  className?: string
}

export function MaxIDCard({
  variant = "active",
  dateGenerated,
  generatedBy,
  onViewCard,
  onExportCard,
  onGenerateCard,
  className,
}: MaxIDCardProps) {
  if (variant === "inactive") {
    return (
      <div
        className={cn(
          "bg-[#f9f8f6] border border-[#f3f3f3] rounded-lg flex flex-col",
          className
        )}
      >
        <div
          className="h-[70px] w-full rounded-t-lg"
          style={{
            backgroundColor: "rgba(255,248,203,0.3)",
            backgroundImage: "url('/images/pattern.svg')",
            backgroundSize: "390px 390px",
            backgroundRepeat: "repeat",
          }}
        />

        <div className="flex items-center gap-2.5 px-6 pt-5">
          <p className="font-bold text-[28px] text-black capitalize">
            MAX ID Card
          </p>
          <div className="pt-2">
            <StatusBadge variant="neutral" withDot size="sm">
              Inactive
            </StatusBadge>
          </div>
        </div>

        <div className="flex items-center justify-between px-6 pt-4 pb-[18px]">
          <p className="font-medium text-[#a0a1a1] text-[13px] tracking-[-0.13px]">
            No ID card has been generated for this champion
          </p>
          <button
            onClick={onGenerateCard}
            className="flex items-center justify-center h-[38px] pl-3 pr-4 bg-white rounded-lg font-medium text-[12.5px] text-[#121314] tracking-[-0.125px] hover:bg-gray-50 transition-colors"
          >
            Generate ID Card
          </button>
        </div>
      </div>
    )
  }

  return (
    <div
      className={cn(
        "bg-[#f9f8f6] border border-[#f3f3f3] rounded-lg flex flex-col",
        className
      )}
    >
      <div
        className="h-[70px] w-full rounded-t-lg"
        style={{
          backgroundColor: "rgba(255,248,203,0.3)",
          backgroundImage: "url('/images/pattern.svg')",
          backgroundSize: "390px 390px",
          backgroundRepeat: "repeat",
        }}
      />

      <div className="flex items-center gap-2.5 px-6 pt-5">
        <p className="font-bold text-[28px] text-black capitalize">
          MAX ID Card
        </p>
        <div className="pt-2">
          <StatusBadge variant="success" withDot size="sm">
            Active
          </StatusBadge>
        </div>
      </div>

      <div className="flex items-center justify-between px-6 pt-4 pb-[18px]">
        <div className="flex items-center gap-10 font-medium capitalize">
          <div className="flex flex-col">
            <span className="text-[#a0a1a1] text-[12px]">Date Generated</span>
            <span className="text-black text-[14px]">{dateGenerated}</span>
          </div>
          <div className="flex flex-col">
            <span className="text-[#a0a1a1] text-[12px]">Generated By</span>
            <span className="text-black text-[14px]">{generatedBy}</span>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={onViewCard}
            className="flex items-center justify-center h-[38px] pl-3 pr-4 bg-white rounded-lg font-medium text-[12.5px] text-[#121314] tracking-[-0.125px] hover:bg-gray-50 transition-colors"
          >
            View ID Card
          </button>
          <button
            onClick={onExportCard}
            className="flex items-center justify-center h-[38px] pl-3 pr-4 bg-white rounded-lg font-medium text-[12.5px] text-[#121314] tracking-[-0.125px] hover:bg-gray-50 transition-colors"
          >
            Export ID Card
          </button>
        </div>
      </div>
    </div>
  )
}
